// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2diAndFI3qM674KTU16U8aBJuJBrARxY',
    appId: '1:17980196565:web:3aeea7a6092bacbe21045c',
    messagingSenderId: '17980196565',
    projectId: 'wordofgod-deeed',
    authDomain: 'wordofgod-deeed.firebaseapp.com',
    storageBucket: 'wordofgod-deeed.firebasestorage.app',
    measurementId: 'G-WT1XHJDZG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJc27HsfMyxXZAF9hDtjUzLvR8U4_4_KM',
    appId: '1:17980196565:android:80049bd768766cdd21045c',
    messagingSenderId: '17980196565',
    projectId: 'wordofgod-deeed',
    storageBucket: 'wordofgod-deeed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATDIipDi6NSFQ1aLc5IkyixEXzoiExULs',
    appId: '1:17980196565:ios:a2c1f6ac56060a6a21045c',
    messagingSenderId: '17980196565',
    projectId: 'wordofgod-deeed',
    storageBucket: 'wordofgod-deeed.firebasestorage.app',
    iosBundleId: 'com.example.god',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATDIipDi6NSFQ1aLc5IkyixEXzoiExULs',
    appId: '1:17980196565:ios:a2c1f6ac56060a6a21045c',
    messagingSenderId: '17980196565',
    projectId: 'wordofgod-deeed',
    storageBucket: 'wordofgod-deeed.firebasestorage.app',
    iosBundleId: 'com.example.god',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2diAndFI3qM674KTU16U8aBJuJBrARxY',
    appId: '1:17980196565:web:b6d6b5517443561121045c',
    messagingSenderId: '17980196565',
    projectId: 'wordofgod-deeed',
    authDomain: 'wordofgod-deeed.firebaseapp.com',
    storageBucket: 'wordofgod-deeed.firebasestorage.app',
    measurementId: 'G-SJYMSVN3K6',
  );
}
